package edu.mit.cci.amtprojects.solver.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.mit.cci.amtprojects.kickball.cayenne.Batch;
import edu.mit.cci.amtprojects.solver.Solution;

/**
 * Class _Question was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Question extends CayenneDataObject {

    public static final String TEXT_PROPERTY = "text";
    public static final String TO_BATCH_PROPERTY = "toBatch";
    public static final String TO_SOLUTIONS_PROPERTY = "toSolutions";

    public static final String ID_PK_COLUMN = "id";

    public void setText(String text) {
        writeProperty("text", text);
    }
    public String getText() {
        return (String)readProperty("text");
    }

    public void setToBatch(Batch toBatch) {
        setToOneTarget("toBatch", toBatch, true);
    }

    public Batch getToBatch() {
        return (Batch)readProperty("toBatch");
    }


    public void addToToSolutions(Solution obj) {
        addToManyTarget("toSolutions", obj, true);
    }
    public void removeFromToSolutions(Solution obj) {
        removeToManyTarget("toSolutions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Solution> getToSolutions() {
        return (List<Solution>)readProperty("toSolutions");
    }


}
