package edu.mit.cci.amtprojects.solver.cayenne;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import edu.mit.cci.amtprojects.solver.Solution;

/**
 * Class _SolutionRank was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SolutionRank extends CayenneDataObject {

    public static final String DATE_PROPERTY = "date";
    public static final String HIT_ID_PROPERTY = "hitId";
    public static final String RANK_PROPERTY = "rank";
    public static final String ROUND_PROPERTY = "round";
    public static final String TO_SOLUTION_PROPERTY = "toSolution";

    public static final String ID_PK_COLUMN = "id";

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setHitId(String hitId) {
        writeProperty("hitId", hitId);
    }
    public String getHitId() {
        return (String)readProperty("hitId");
    }

    public void setRank(String rank) {
        writeProperty("rank", rank);
    }
    public String getRank() {
        return (String)readProperty("rank");
    }

    public void setRound(Integer round) {
        writeProperty("round", round);
    }
    public Integer getRound() {
        return (Integer)readProperty("round");
    }

    public void setToSolution(Solution toSolution) {
        setToOneTarget("toSolution", toSolution, true);
    }

    public Solution getToSolution() {
        return (Solution)readProperty("toSolution");
    }


}
