package edu.mit.cci.amtprojects.solver.auto;

import org.apache.cayenne.CayenneDataObject;

import edu.mit.cci.amtprojects.kickball.cayenne.Users;

/**
 * Class _AwsCredentials was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AwsCredentials extends CayenneDataObject {

    public static final String AWS_ID_PROPERTY = "awsId";
    public static final String AWS_SECRET_PROPERTY = "awsSecret";
    public static final String USER_PROPERTY = "user";

    public static final String ID_PK_COLUMN = "id";

    public void setAwsId(String awsId) {
        writeProperty("awsId", awsId);
    }
    public String getAwsId() {
        return (String)readProperty("awsId");
    }

    public void setAwsSecret(String awsSecret) {
        writeProperty("awsSecret", awsSecret);
    }
    public String getAwsSecret() {
        return (String)readProperty("awsSecret");
    }

    public void setUser(Users user) {
        setToOneTarget("user", user, true);
    }

    public Users getUser() {
        return (Users)readProperty("user");
    }


}
