package edu.mit.cci.amtprojects.kickball.cayenne;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.mit.cci.amtprojects.solver.Question;

/**
 * Class _Batch was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Batch extends CayenneDataObject {

    public static final String AWS_ID_PROPERTY = "awsId";
    public static final String AWS_SECRET_PROPERTY = "awsSecret";
    public static final String CREATED_PROPERTY = "created";
    public static final String IS_REAL_PROPERTY = "isReal";
    public static final String NAME_PROPERTY = "name";
    public static final String PARAMETERS_PROPERTY = "parameters";
    public static final String TO_EXPERIMENT_PROPERTY = "toExperiment";
    public static final String TO_LOGS_PROPERTY = "toLogs";
    public static final String TO_QUESTION_PROPERTY = "toQuestion";
    public static final String TO_STATUS_PROPERTY = "toStatus";

    public static final String ID_PK_COLUMN = "id";

    public void setAwsId(String awsId) {
        writeProperty("awsId", awsId);
    }
    public String getAwsId() {
        return (String)readProperty("awsId");
    }

    public void setAwsSecret(String awsSecret) {
        writeProperty("awsSecret", awsSecret);
    }
    public String getAwsSecret() {
        return (String)readProperty("awsSecret");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIsReal(Boolean isReal) {
        writeProperty("isReal", isReal);
    }
    public Boolean getIsReal() {
        return (Boolean)readProperty("isReal");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setParameters(String parameters) {
        writeProperty("parameters", parameters);
    }
    public String getParameters() {
        return (String)readProperty("parameters");
    }

    public void setToExperiment(Experiment toExperiment) {
        setToOneTarget("toExperiment", toExperiment, true);
    }

    public Experiment getToExperiment() {
        return (Experiment)readProperty("toExperiment");
    }


    public void addToToLogs(TurkerLog obj) {
        addToManyTarget("toLogs", obj, true);
    }
    public void removeFromToLogs(TurkerLog obj) {
        removeToManyTarget("toLogs", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TurkerLog> getToLogs() {
        return (List<TurkerLog>)readProperty("toLogs");
    }


    public void addToToQuestion(Question obj) {
        addToManyTarget("toQuestion", obj, true);
    }
    public void removeFromToQuestion(Question obj) {
        removeToManyTarget("toQuestion", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Question> getToQuestion() {
        return (List<Question>)readProperty("toQuestion");
    }


    public void addToToStatus(BatchStatus obj) {
        addToManyTarget("toStatus", obj, true);
    }
    public void removeFromToStatus(BatchStatus obj) {
        removeToManyTarget("toStatus", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BatchStatus> getToStatus() {
        return (List<BatchStatus>)readProperty("toStatus");
    }


}
