package edu.mit.cci.amtprojects.kickball.cayenne;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _BatchStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BatchStatus extends CayenneDataObject {

    public static final String CREATION_PROPERTY = "creation";
    public static final String JSON_STATUS_PROPERTY = "jsonStatus";
    public static final String TO_BATCH_PROPERTY = "toBatch";

    public static final String ID_PK_COLUMN = "id";

    public void setCreation(Date creation) {
        writeProperty("creation", creation);
    }
    public Date getCreation() {
        return (Date)readProperty("creation");
    }

    public void setJsonStatus(String jsonStatus) {
        writeProperty("jsonStatus", jsonStatus);
    }
    public String getJsonStatus() {
        return (String)readProperty("jsonStatus");
    }

    public void setToBatch(Batch toBatch) {
        setToOneTarget("toBatch", toBatch, true);
    }

    public Batch getToBatch() {
        return (Batch)readProperty("toBatch");
    }


}
