package edu.mit.cci.amtprojects.kickball.cayenne;

import java.lang.*;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Post was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Post extends CayenneDataObject {

    public static final String CONTENT_PROPERTY = "content";
    public static final String CREATED_PROPERTY = "created";
    public static final String EVENT_SESSION_PROPERTY = "eventSession";
    public static final String IP_ADDRESS_PROPERTY = "ipAddress";
    public static final String POSTID_PROPERTY = "postid";
    public static final String THREADID_PROPERTY = "threadid";
    public static final String POST_TO_THREAD_PROPERTY = "postToThread";
    public static final String POST_TO_USER_PROPERTY = "postToUser";
    public static final String QUOTED_BY_PROPERTY = "quotedBy";
    public static final String QUOTES_PROPERTY = "quotes";

    public static final String POSTID_PK_COLUMN = "postid";

    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEventSession(Integer eventSession) {
        writeProperty("eventSession", eventSession);
    }
    public Integer getEventSession() {
        return (Integer)readProperty("eventSession");
    }

    public void setIpAddress(String ipAddress) {
        writeProperty("ipAddress", ipAddress);
    }
    public String getIpAddress() {
        return (String)readProperty("ipAddress");
    }

    public void setPostid(Integer postid) {
        writeProperty("postid", postid);
    }
    public Integer getPostid() {
        return (Integer)readProperty("postid");
    }

    public void setThreadid(Integer threadid) {
        writeProperty("threadid", threadid);
    }
    public Integer getThreadid() {
        return (Integer)readProperty("threadid");
    }

    public void setPostToThread(Thread postToThread) {
        setToOneTarget("postToThread", postToThread, true);
    }

    public java.lang.Thread getPostToThread() {
        return (java.lang.Thread)readProperty("postToThread");
    }


    public void setPostToUser(User postToUser) {
        setToOneTarget("postToUser", postToUser, true);
    }

    public User getPostToUser() {
        return (User)readProperty("postToUser");
    }


    public void addToQuotedBy(Post obj) {
        addToManyTarget("quotedBy", obj, true);
    }
    public void removeFromQuotedBy(Post obj) {
        removeToManyTarget("quotedBy", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Post> getQuotedBy() {
        return (List<Post>)readProperty("quotedBy");
    }


    public void addToQuotes(Post obj) {
        addToManyTarget("quotes", obj, true);
    }
    public void removeFromQuotes(Post obj) {
        removeToManyTarget("quotes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Post> getQuotes() {
        return (List<Post>)readProperty("quotes");
    }


}
