package edu.mit.cci.amtprojects.kickball.cayenne;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Quote was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Quote extends CayenneDataObject {

    public static final String FROM_POST_PROPERTY = "fromPost";
    public static final String TO_QUOTE_PROPERTY = "toQuote";

    public static final String REL_ID_PK_COLUMN = "relId";

    public void setFromPost(Post fromPost) {
        setToOneTarget("fromPost", fromPost, true);
    }

    public Post getFromPost() {
        return (Post)readProperty("fromPost");
    }


    public void setToQuote(Post toQuote) {
        setToOneTarget("toQuote", toQuote, true);
    }

    public Post getToQuote() {
        return (Post)readProperty("toQuote");
    }


}
