package edu.mit.cci.amtprojects.kickball.cayenne;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Thread was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Thread extends CayenneDataObject {

    public static final String ENDDATE_PROPERTY = "enddate";
    public static final String STARTDATE_PROPERTY = "startdate";
    public static final String THREADID_PROPERTY = "threadid";
    public static final String THREAD_TO_POST_PROPERTY = "threadToPost";

    public static final String THREADID_PK_COLUMN = "threadid";

    public void setEnddate(Date enddate) {
        writeProperty("enddate", enddate);
    }
    public Date getEnddate() {
        return (Date)readProperty("enddate");
    }

    public void setStartdate(Date startdate) {
        writeProperty("startdate", startdate);
    }
    public Date getStartdate() {
        return (Date)readProperty("startdate");
    }

    public void setThreadid(Integer threadid) {
        writeProperty("threadid", threadid);
    }
    public Integer getThreadid() {
        return (Integer)readProperty("threadid");
    }

    public void addToThreadToPost(Post obj) {
        addToManyTarget("threadToPost", obj, true);
    }
    public void removeFromThreadToPost(Post obj) {
        removeToManyTarget("threadToPost", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Post> getThreadToPost() {
        return (List<Post>)readProperty("threadToPost");
    }


}
