package edu.mit.cci.amtprojects.kickball.cayenne;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _TurkerLog was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TurkerLog extends CayenneDataObject {

    public static final String DATE_PROPERTY = "date";
    public static final String POST_PROPERTY = "post";
    public static final String REPLYTO_PROPERTY = "replyto";
    public static final String TO_BATCH_PROPERTY = "toBatch";

    public static final String ID_PK_COLUMN = "id";

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setPost(Long post) {
        writeProperty("post", post);
    }
    public Long getPost() {
        return (Long)readProperty("post");
    }

    public void setReplyto(Long replyto) {
        writeProperty("replyto", replyto);
    }
    public Long getReplyto() {
        return (Long)readProperty("replyto");
    }

    public void setToBatch(Batch toBatch) {
        setToOneTarget("toBatch", toBatch, true);
    }

    public Batch getToBatch() {
        return (Batch)readProperty("toBatch");
    }


}
