package edu.mit.cci.amtprojects.kickball.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String USER_ID_PROPERTY = "userId";
    public static final String USERNAME_PROPERTY = "username";
    public static final String USER_TO_POST_PROPERTY = "userToPost";

    public static final String ID_PK_COLUMN = "id";

    public void setUserId(int userId) {
        writeProperty("userId", userId);
    }
    public int getUserId() {
        Object value = readProperty("userId");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void addToUserToPost(Post obj) {
        addToManyTarget("userToPost", obj, true);
    }
    public void removeFromUserToPost(Post obj) {
        removeToManyTarget("userToPost", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Post> getUserToPost() {
        return (List<Post>)readProperty("userToPost");
    }


}
